#!/bin/sh
xhost local:root
#wlpinyin&
#chmod 2770 -R /tmp/*
waybar&
swaybg -i /home/stem/wallpapers/deimos.jpg&
riverctl input 1739:32382:PNP0C50:0e_06CB:7E7E_Touchpad tap enabled
# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal Super T spawn foot

# Super+Q to close the focused view
riverctl map normal Super+Shift Q close

# Super+Shift+E to exit river
riverctl map normal Super+Shift Backspace exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Control J swap next
riverctl map normal Super+Control K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Control H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Control L send-layout-cmd rivertile "main-count -1"

# move views
riverctl map -repeat normal Super+Shift H move left 20
riverctl map -repeat normal Super+Shift J move down 20
riverctl map -repeat normal Super+Shift K move up 20
riverctl map -repeat normal Super+Shift L move right 20

# snap views to screen edges
riverctl map normal Super+Alt+Shift H snap left
riverctl map normal Super+Alt+Shift J snap down
riverctl map normal Super+Alt+Shift K snap up
riverctl map normal Super+Alt+Shift L snap right

# resize views
riverctl map -repeat normal Super+Alt L resize horizontal -40
riverctl map -repeat normal Super+Alt K resize vertical 40
riverctl map -repeat normal Super+Alt J resize vertical -40
riverctl map -repeat normal Super+Alt H resize horizontal 40

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    #riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map -repeat $mode None XF86AudioRaiseVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ +5%'
    riverctl map -repeat $mode None XF86AudioLowerVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ -5%'
    riverctl map -repeat $mode None XF86AudioMute         spawn 'pactl set-sink-mute @DEFAULT_SINK@ toggle'
    riverctl map -repeat $mode None XF86AudioMicMute      spawn 'pactl set-source-mute @DEFAULT_SOURCE@ toggle'
# Screenshot capabilities
    riverctl map normal Super S spawn 'bash /home/stem/scripts/window.sh'
    riverctl map normal Super W spawn 'grim - |tee /home/stem/screenshots/$(date +whole-%F-%H-%M-%S.png)| wl-copy -t image/png'
# Recording capabilities
	riverctl map normal Super U spawn 'killall -s SIGINT wf-recorder'
	riverctl map normal Super I spawn 'wf-recorder -r30 -aalsa_output.pci-0000_03_00.6.analog-stereo.monitor -g"$(slurp)" -f/home/stem/recordings/$(date +%F-%H-%M-%S.mp4)' 
	riverctl map normal Super O spawn 'wf-recorder -r30 -aalsa_output.pci-0000_03_00.6.analog-stereo.monitor -f/home/stem/recordings/$(date +whole-%F-%H-%M-%S.mp4)' 
	#riverctl map normal Super I spawn 'wf-recorder -r30 -aCombined.monitor -g"$(slurp)" -f/home/stem/recordings/$(date +%F-%H-%M-%S.mp4)' 
	
	#riverctl map normal Super O spawn 'wf-recorder -r30 -aCombined.monitor -f/home/stem/recordings/$(date +whole-%F-%H-%M-%S.mp4)'
# Launcher
    riverctl map normal Super G spawn 'bemenu-run --center -l 6 -p ">" -M 850 --fn 15 -B 2 --bdr "#ff0000" --ab "#000000" --af "#ffffff" --nb "#000000" --nf "#ffffff" --tb "#000000" --tf "#ff0000" --fb "#000000" --ff "#ffffff" --hb "#000000" --hf "#ff0000"'
    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    #riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause' riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    #riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    #riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    #riverctl map -repeat normal Super R spawn 'light -s sysfs/backlight/amdgpu_bl0 -A 5'
    #riverctl map -repeat normal Super E spawn 'light -s sysfs/backlight/amdgpu_bl0 -U 5'
    riverctl map -repeat normal Super R spawn 'light -A 5'
    riverctl map -repeat normal Super E spawn 'light -U 5'
done

# Set background and border color
riverctl background-color 0x000000
riverctl border-color-focused 0xff0000
riverctl border-color-unfocused 0x666666

# Set keyboard repeat rate
riverctl set-repeat 100 200

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "popup title with spaces"

# Set app-ids and titles of views which should use client side decorations
riverctl csd-filter-add app-id "gedit"

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -main-ratio 0.5 -view-padding 3 -outer-padding 3
